apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: will518/course-platform
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-secret
                  key: REACT_APP_CLERK_PUBLISHABLE_KEY
